[package]
name = "arrange_it"
version = "0.1.0"
authors = ["lee <lee-dasilva@hotmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.13.0"
