name: GA-Run-All-Rust-Test
on:
  pull_request:
    branches: ['master']
  # workflow_run:
  #   workflows: ['Docker Image On Branch CI']
  #   types:
  #     - completed
  # workflow_run:
  #   workflows: ['Docker Image CI']
  #   types:
  #     - completed

env:
  BRANCH_ID: ${{ github.event.pull_request.number }}

jobs:
  GA-All-Rust-Test:
    runs-on: ga-test-runner-check-rust-tests
    steps:
      - name: 🐧  Check out repository code
        uses: actions/checkout@v3
        with:
          ssh: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: 'Launch script with branch $BRANCH_ID'
        run: |
          pwd
          ls -la
          ./tests/test_exercises.sh \
          -real \
          -n \
          -pull-from \
          test-rust:PR${{ github.event.pull_request.number }}
